const sampleData = {
    products: [
      {
        name: 'Billiard Ball Set',
        slug: 'billiard-ball-set',
        category: 'sports',
        images: ['/assets/images/img1.jpg'],
        price: 100,
        brand: 'ProSports',
        rating: 4.5,
        numReviews: 10,
        stock: 20,
        description: 'A set of 9 billiard balls for pool and snooker.',
        isFeatured: true,
        banner: '/assets/images/banner1.jpg',
      },
      {
        name: 'Ping Pong Balls',
        slug: 'ping-pong-balls',
        category: 'sports',
        images: ['/assets/images/img2.jpg'],
        price: 50,
        brand: 'PingPro',
        rating: 4.2,
        numReviews: 15,
        stock: 30,
        description: 'High-quality ping pong balls for professional use.',
        isFeatured: true,
        banner: '/assets/images/banner2.jpg',
      },
      {
        name: 'Golf Balls',
        slug: 'golf-balls',
        category: 'sports',
        images: ['/assets/images/img3.jpg'],
        price: 120,
        brand: 'GolfMaster',
        rating: 4.7,
        numReviews: 8,
        stock: 25,
        description: 'Premium golf balls with great control and spin.',
        isFeatured: false,
        banner: '/assets/images/banner3.jpg',
      },
      {
        name: 'Basketball',
        slug: 'basketball',
        category: 'sports',
        images: ['/assets/images/img4.jpg'],
        price: 150,
        brand: 'HoopStar',
        rating: 4.6,
        numReviews: 20,
        stock: 15,
        description: 'Durable basketball suitable for indoor and outdoor play.',
        isFeatured: true,
        banner: '/assets/images/banner4.jpg',
      },
      {
        name: 'Soccer Ball',
        slug: 'soccer-ball',
        category: 'sports',
        images: ['/assets/images/img5.jpg'],
        price: 80,
        brand: 'GoalPro',
        rating: 4.4,
        numReviews: 12,
        stock: 18,
        description: 'Professional-grade soccer ball for matches and training.',
        isFeatured: false,
        banner: '/assets/images/banner5.jpg',
      },
    ],
  };
  
  export default sampleData;
  